version: '2'
services:
  main:
    build: ./
    restart: always
    privileged: true
    # command: ["sleep", "infinity"]
    labels:
      io.resin.features.dbus: '1'
      io.resin.features.kernel-modules: '1'
      io.resin.features.firmware: '1'
    environment:
      - UDEV=1
    ## ======= Uncomment these for local Docker testing. =======
    ##         On Mac, make sure you have XQuartz
    ##         running and have run `xhost +`.
      # - DISPLAY=host.docker.internal:0
      # - UDEV=0
